Downgrade to Cairo 2.0.0
keep-starknet-strange/alexandria pull request #144
Opened 2023-07-25 13:44 UTC by delaaxe

`2.0.1` isn't supported on any testnet so addings alexandria as a dependency to any project makes it undeployable to any network currently.

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [X] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

2023-07-25 13:45 UTC, delaaxe commented
@LucasLvy

2023-07-25 19:45 UTC, LucasLvy commented
You can specify a commit/branch using scarb so I don't think it should be on main. I can create a specific branch for that WDYT ?

2023-07-25 19:46 UTC, delaaxe commented
Sure, if we can document the syntax for specifying the branch

2023-07-27 08:15 UTC, LucasLvy requested changes

2023-07-27 08:15 UTC, LucasLvy commented on Scarb.toml
> +starknet = ">=2.0.0"
Shouldn't this be like that ?
```suggestion
starknet = "=2.0.0"
```

2023-07-27 09:11 UTC, LucasLvy commented
you probably need to downgrade scarb also

2023-07-31 17:05 UTC, delaaxe commented
`2.1` will be on testnet next week so not sure this is needed anymore

2023-07-31 17:05 UTC, closed without merging