Feat BitArray adds data structure for read/writing unary bits and encoding words in big/little endian notation
keep-starknet-strange/alexandria pull request #191
Opened 2023-10-12 17:49 UTC by sveamarcus

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

- Adds a BitArray that can read/write unary bits as well as words of all sizes
- Supports encoding/decoding words in both big and little endian
- Packs bits within a bytes31 array
- Serialization and deserialization through Serde

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2023-10-16 07:57 UTC, LucasLvy requested changes

2023-10-16 07:57 UTC, LucasLvy commented on src/data_structures/src/bit_array.cairo
> +        let u256{low, high } = word;
```suggestion
        let u256 { low, high } = word;
```

2023-10-16 07:57 UTC, LucasLvy commented on src/data_structures/src/bit_array.cairo
> +        let u512{limb0, limb1, limb2, limb3 } = word;
```suggestion
        let u512 { limb0, limb1, limb2, limb3 } = word;
```

2023-10-16 14:33 UTC, sveamarcus commented
The suggested changes did not pass `test / check-format` check phase. I recommitted the files after scarb fmt. Hope that helps.

2023-10-17 09:34 UTC, LucasLvy approved these changes

2023-10-17 09:34 UTC, merged