feat: generic byte reader reopen
keep-starknet-strange/alexandria pull request #225
Opened 2023-12-07 10:36 UTC by sveamarcus

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

Please see pull request 199 for background. Reopened here minus Serde which has been added to `byte_array` of `core`.

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2023-12-08 10:05 UTC, LucasLvy requested changes

2023-12-11 12:45 UTC, sveamarcus commented on src/data_structures/src/byte_reader.cairo
> +    fn remaining(self: @T, at: usize, count: usize) -> Option<()>;
agreed, it saves a couple of lines of code below but it's unnecessarily complicated

2023-12-11 14:27 UTC, sveamarcus commented
> also can you check if `ByteArray` doesn't suit all your needs ?

Can you elaborate a bit please? Which part were you thinking of?

2023-12-11 14:28 UTC, LucasLvy reviewed
parse_signed already returns an option so no need to do `Option::Some(pars_signed(x, y)?)` just return `parse_signed(x, y)`

2023-12-12 09:18 UTC, merged