Signed u256 aka i257
keep-starknet-strange/alexandria pull request #236
Opened 2024-01-04 11:23 UTC by shramee

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

We don't have signed u256.

Issue Number: N/A

## What is the new behavior?

We have signed u256.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

The code and tests for this is largely taken from old i129 int. I've tried to make commits with old pasted code and tweaks made on that commit. Hopefully that will make reviewing easier.

Source: https://github.com/shramee/alexandria/blob/7e0f050b97c42b2a5916d552494d3724ae2c0197/alexandria/math/src/signed_integers.cairo#L1618

Tests come from: https://github.com/shramee/alexandria/blob/7e0f050b97c42b2a5916d552494d3724ae2c0197/alexandria/math/src/tests/signed_integers_test.cairo#L1279

2024-01-04 22:25 UTC, shramee commented
I'm using i257 for Euclidean algorithm implementation of `alexandria_math::mod_arithmetics`.
![image](https://github.com/keep-starknet-strange/alexandria/assets/11048263/b99d49eb-0704-4f1e-b23b-34d6a297253b)

https://x.com/shrameetweets/status/1743034431521124704?s=20

2024-01-05 12:03 UTC, LucasLvy requested changes

2024-01-05 12:03 UTC, LucasLvy commented on src/math/src/signed_u256.cairo
> +}
why not put this directly in the trait impl ?

2024-01-05 12:03 UTC, LucasLvy commented on src/math/src/signed_u256.cairo
> +}
same here and for all others

2024-01-06 09:39 UTC, shramee commented on src/math/src/signed_u256.cairo
> +}
`DivRem` traits needs external type `NonZero`. I'm having trouble finding a way to build `NonZero<i257>`, is this possible?

2024-01-06 09:40 UTC, shramee commented on src/math/src/signed_u256.cairo
> +}
Done

2024-01-06 09:44 UTC, shramee commented on src/math/src/signed_u256.cairo
> +}
I've added the trait, but not sure how to test this because of the `NonZero` issue above...

2024-01-08 10:17 UTC, LucasLvy commented on src/math/src/signed_u256.cairo
> +}
nah you're right it's not possible

2024-01-08 10:18 UTC, LucasLvy requested changes
revert the `DivRem` plz otherwise lgtm

2024-01-12 13:49 UTC, LucasLvy approved these changes

2024-01-12 13:49 UTC, merged