feat: add fast trigonometric functions
keep-starknet-strange/alexandria pull request #243
Opened 2024-01-17 06:02 UTC by Soptq

This PR adds fast trigonometric functions (sin, cos, tan) to the library. Compared to standard trigonometric functions, fast trigonometric functions are computational and spacial efficient, with minor (acceptable errors).

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

- Add fast trigonometric functions (sin, cos, tan) to the library
- All tests are passed

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2024-01-19 15:12 UTC, LucasLvy requested changes

2024-01-19 15:12 UTC, LucasLvy commented on src/math/src/trigonometry.cairo
> +    let multipier = 100000000_u64;
use `consteval_int`

2024-01-19 15:12 UTC, LucasLvy commented on src/math/src/trigonometry.cairo
> +fn fast_tan(x: u64) -> (bool, u64) {
use `i64`

2024-01-19 15:12 UTC, LucasLvy commented on src/math/src/trigonometry.cairo
> +fn fast_sin(x: u64) -> (bool, u64) {
use `i64`

2024-01-19 18:35 UTC, Soptq commented on src/math/src/trigonometry.cairo
> +fn fast_tan(x: u64) -> (bool, u64) {
fixed ;)

2024-01-19 18:35 UTC, Soptq commented on src/math/src/trigonometry.cairo
> +    let multipier = 100000000_u64;
fixed ;)

2024-01-19 18:35 UTC, Soptq commented on src/math/src/trigonometry.cairo
> +fn fast_sin(x: u64) -> (bool, u64) {
fixed ;)

2024-01-22 11:04 UTC, LucasLvy commented
why not i64 everywhere ?

2024-01-22 13:50 UTC, Soptq commented
> why not i64 everywhere ?

Thanks @LucasLvy for taking time to review this PR!

It seems that `i64` does not implement `core::traits::Div` and `core::traits::Rem`, which is crucial for the fast trigonometric algorithm. Consequently, I decided to firstly implement `sin(x)` for x > 0, and thereby obtaining `sin(x)`, `cos(x)` and `tan(x)` for x < 0 and x > 0 using symmetry properties.

2024-01-23 09:51 UTC, LucasLvy approved these changes

2024-01-23 09:51 UTC, merged