feat: add fast root using Newton-Raphson method
keep-starknet-strange/alexandria pull request #255
Opened 2024-01-24 15:12 UTC by Soptq

This PR adds fast root using Newton-Raphson method

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

- solving square / cube / N-th root using Newton-Raphson method.
- all tests are passed.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2024-01-24 16:12 UTC, LucasLvy requested changes
Fix doc format and add a precision over each function that the result can be rounded up (which is not usual for ints)

2024-01-24 16:12 UTC, LucasLvy commented on src/math/src/fast_root.cairo
> +use super::pow;
fix import and doc

2024-01-25 02:54 UTC, Soptq commented on src/math/src/fast_root.cairo
> +use super::pow;
Fixed ;)

2024-01-25 11:32 UTC, LucasLvy approved these changes

2024-01-25 11:32 UTC, merged