feat: add lcm of n numbers
keep-starknet-strange/alexandria pull request #256
Opened 2024-01-24 15:13 UTC by Soptq

This PR adds LCM of N numbers.

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

- solving LCM of N numbers.
- all tests are passed.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2024-01-24 16:07 UTC, LucasLvy requested changes
rename the tests to correct names, might also be worth to implement either lcm for any type that implements `Mul` and `Div`(this would require a change in the gcd function) or implement that function for any type that implements `TryInto<..., u128>`

2024-01-24 16:07 UTC, LucasLvy commented on src/math/src/lcm_of_n_numbers.cairo
> +
```suggestion
use alexandria_math::gcd_of_n_numbers::gcd_two_numbers;

/// Calculate the lowest common multiple for n numbers
/// # Arguments
/// * `n` - The array of numbers to calculate the lcm for
/// # Returns
/// * `u128` - The lcm of input numbers
```

2024-01-24 16:07 UTC, LucasLvy commented on src/math/src/lcm_of_n_numbers.cairo
> +fn lcm(mut n: Span<u128>) -> u128 {
return a result don't panic

2024-01-24 16:07 UTC, LucasLvy commented on src/math/src/lcm_of_n_numbers.cairo
> +        panic_with_felt252('EI')
```suggestion
        return Result::Err(....)
```

2024-01-25 02:55 UTC, Soptq commented on src/math/src/lcm_of_n_numbers.cairo
> +
Fixed ;)

2024-01-25 02:55 UTC, Soptq commented on src/math/src/lcm_of_n_numbers.cairo
> +        panic_with_felt252('EI')
Fixed ;)

2024-01-25 02:56 UTC, Soptq commented on src/math/src/lcm_of_n_numbers.cairo
> +fn lcm(mut n: Span<u128>) -> u128 {
Fixed ;)

2024-01-25 03:02 UTC, Soptq commented
> rename the tests to correct names, might also be worth to implement either lcm for any type that implements `Mul` and `Div`(this would require a change in the gcd function) or implement that function for any type that implements `TryInto<..., u128>`

Thanks for the advice, it is now done ;)

2024-01-25 11:31 UTC, LucasLvy requested changes
Sorry i'm dumb i meant `Into<T, u128>` not `TryInto` can you change that plz

2024-01-25 13:54 UTC, LucasLvy approved these changes

2024-01-25 13:54 UTC, merged