feat: add norm
keep-starknet-strange/alexandria pull request #266
Opened 2024-01-25 13:38 UTC by Soptq

This PR adds `norm` operator.

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

- calculating Norm of a given list.
- all tests are passed.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2024-01-25 13:57 UTC, LucasLvy requested changes

2024-01-25 13:57 UTC, LucasLvy commented on src/linalg/src/norm.cairo
> +fn norm(mut xs: Span<u128>, ord: u128, iter: usize) -> u128 {
`Into<T, u128`?

2024-01-25 15:24 UTC, Soptq commented on src/linalg/src/norm.cairo
> +fn norm(mut xs: Span<u128>, ord: u128, iter: usize) -> u128 {
Fixed ;)

2024-01-26 10:49 UTC, LucasLvy requested changes

2024-01-26 10:49 UTC, LucasLvy commented on src/linalg/src/norm.cairo
> +    norm
```suggestion
    fast_nr_optimize(norm, ord, iter)
```

2024-01-26 13:32 UTC, LucasLvy approved these changes

2024-01-26 13:32 UTC, merged

2024-01-26 13:58 UTC, Soptq commented on src/linalg/src/tests/norm_test.cairo
> +    let mut array: Array<u128> = array![3, 4];
Thanks for reviewing, this is fixed in this PR: https://github.com/keep-starknet-strange/alexandria/pull/268