Fix merkle tree hashes for poseidon
keep-starknet-strange/alexandria pull request #277
Opened 2024-02-19 11:59 UTC by Leonard-Pat

## Pull Request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

The current Poseidon hashing implementation for the merkle tree is incorrect. It uses 
```
            let mut state = PoseidonTrait::new();
            state = state.update(data1);
            state = state.update(data2);
            state.finalize()

```
Under the hood this actually hashes the elements twice  (once from the state update and once from finalization, see [corelib](https://github.com/starkware-libs/cairo/blob/main/corelib/src/poseidon.cairo)), the intended behaviours is that only one round of hashing is done (when hashing two elements). This is noted in https://docs.starknet.io/documentation/architecture_and_concepts/Cryptography/hash-functions/#poseidon_hash where by the hash of two elements is simply 
<img width="417" alt="Screenshot 2024-02-19 at 11 53 04" src="https://github.com/keep-starknet-strange/alexandria/assets/106159231/b4421134-d522-4ab6-be62-e41f61e335a4">. 
Also please see POC https://github.com/Leonard-Pat/merkle-tree-failing 

- Fixes Poseidon hashing for merkle tree poseidon impl

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Updated tests to reflect this change - note the gas limit was exceeded and therefore needed to be udpated as well

2024-02-19 13:52 UTC, LucasLvy requested changes
can you also fix pedersen plz

2024-02-19 14:30 UTC, Leonard-Pat commented
> can you also fix pedersen plz

Pedersen is i believe is correct as the finalization step does not add another round of hashing

2024-02-20 09:26 UTC, LucasLvy commented
ah indeed but i think that using directly the `pedersen` function would reduce a bit the step cost

2024-02-20 09:42 UTC, Leonard-Pat commented
> ah indeed but i think that using directly the `pedersen` function would reduce a bit the step cost

okay done :)

2024-02-20 09:46 UTC, LucasLvy approved these changes

2024-02-20 09:50 UTC, merged