Fixing i257 is_zero()
keep-starknet-strange/alexandria pull request #282
Opened 2024-03-01 16:38 UTC by gaetbout

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

Fixing is_zero behaviour that was causing is_zero to sometimes return false when it was indeed zero

2024-03-01 20:02 UTC, delaaxe commented
this solution preserves negative zeros which shouldn't be allowed

2024-03-01 22:20 UTC, gaetbout commented
You saying it shouldn't be possible to create `i257 { abs: 0, is_negative: true };` ?
I'm afraid this would add a lot of `Result` to handle that case then

2024-03-01 22:42 UTC, delaaxe commented
Check out the other functions, they already panic when that's the case

2024-03-06 10:24 UTC, LucasLvy requested changes
should panic for negative zero

2024-03-06 18:19 UTC, gaetbout commented
How should I enforce that?
The `i257_new()` fn already enforces that it can't be done, if the user creates it manually, there is nothing I can do.
Am I missing something?

2024-03-06 19:10 UTC, LucasLvy commented
Add and assertion in the function

2024-03-07 14:59 UTC, LucasLvy approved these changes

2024-03-07 15:03 UTC, merged